enyo.depends(
  "dimple/lib/d3.v3.4.8.min.js",
  "dimple/dist/dimple.v2.0.2.min.js",
  "RGraph/libraries/RGraph.common.core.js",
  "RGraph/libraries/RGraph.funnel.js",
  "RGraph/libraries/RGraph.common.tooltips.js",
  "RGraph/libraries/RGraph.common.dynamic.js",
  "leaflet/dist/leaflet.css",
  "leaflet/dist/leaflet-src.js",
  "leaflet-markercluster/dist/leaflet.markercluster-src.js",
  "leaflet-markercluster/dist/MarkerCluster.css",
  "leaflet-markercluster/dist/MarkerCluster.Default.css",
  "leaflet-label/dist/leaflet.label.js",
  "leaflet-label/dist/leaflet.label.css",
  "leaflet-providers/leaflet-providers.js"
);
